on:
  workflow_call:
    inputs:
      is_tag:
        description: 'Is a Git Tag'
        type: string
        required: true
      current_branch_tag:
        description: 'Git branch or Tag'
        type: string
        required: true
      stable_unstable:
        description: 'stable/unstable'
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:

  build-macos-package:
    name: build-macos-package
    runs-on: "ubuntu-latest"

    steps:

    - uses: actions/checkout@v3

    - name: Build MacOS Package
      run: ./build-macos-package.sh is_tag=${{ inputs.is_tag }} stable_unstable=${{ inputs.stable_unstable }} current_branch_tag=${{ inputs.current_branch_tag }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
